#!/usr/local/bin/ruby

require 'pp'
require 'pathname'
require 'yaml'
require "resolv"
require "socket"
require "net/http"
require "uri"
require 'timeout'

RESOLV_TIMEOUT = 10
CURRENT_PATH = Pathname.new(__FILE__).realpath.dirname.to_s
@config = YAML.load_file(CURRENT_PATH + "/config.yml")
@label = '未知'
# 设置已知宿主的名称和 dns
if @config["hosts"].has_key? Socket.gethostname
  host = @config["hosts"][Socket.gethostname]
  @label = host["label"]
  @dns = host["dns"]
end

def alert_im(msg)
  url = URI.parse("http://api.fanfou.com/statuses/update.xml")
  req = Net::HTTP::Post.new(url.path)
  req.basic_auth @config['fanfou']['username'], @config['fanfou']['password']
  req.set_form_data({ 'status' => msg }, ';')
  res = Net::HTTP.start(url.host, url.port) { |http| http.request(req) }
end

@config["targets"].each {|target|
#  Thread.new {
    url = URI.parse(target['url'])
    ips = []
    unless @dns.nil?
      res = Resolv::DNS.new(:nameserver => @dns, :search => [''], :ndots => 1)
    else
      res = Resolv::DNS.new()
    end
    # 开始解析 DNS，控制超时
    begin
      Timeout::timeout(RESOLV_TIMEOUT) {
        res.each_address(url.host) do |ip|
          ip = ip.to_s
          ips.delete_if {|x| x == ip }
          ips.push(ip)
        end
      }
    rescue Timeout::Error
      alert_im "DNS解析超过#{RESOLV_TIMEOUT}秒 @#{@label}"
    end
    ips.each {|ip|
#      Thread.new {
        msg = "[#{Time.now.strftime('%H:%M:%S')}] #{url.host}:#{ip} @#{@label} "
        req = Net::HTTP::Get.new(url.path)
        req.add_field 'Host', url.host
        unless target.index("bytes_range").nil?
          ma = target.index("bytes_range").match(/^(\d+)\.\.(\d+)$/)
          req.set_range ma[0].to_i, ma[1].to_i
        end
        begin
          http = Net::HTTP.new(ip, url.port)
      #    http.open_timeout = 1
      #    http.read_timeout = 1
      #    http.set_debug_output $stderr
          res = nil
          status = Timeout::timeout(target['timeout']) { res = http.request(req) }
          case res
          when Net::HTTPSuccess
          else
            alert_im "#{msg}" + res.error
          end
        rescue Timeout::Error
          msg += "#{target['timeout']}超时"
          unless target.index("bytes_range").nil?
            size = res.read_body.length
            rate = size / target.timeout / 1024
            msg += " #{rate}/秒"
          end
          alert_im msg
        end
        puts msg + " OK"
#      }
    }
#  }
}
